version: 2.1

orbs:

  maven-cache:
    commands:
      with:
        parameters:
          cache-key:
            default: deps.edn
            type: string
          cache-version:
            default: ""
            type: string
          steps:
            type: steps
        steps:
          - restore_cache:
              key: maven-<< parameters.cache-version >>-{{ checksum "<< parameters.cache-key >>" }}
          - steps: << parameters.steps >>
          - save_cache:
              key: maven-<< parameters.cache-version >>-{{ checksum "<< parameters.cache-key >>" }}
              paths:
                - ~/.m2/repository

#
# clj-service orb
# - build: builds a clojure service docker image and persists it to workspace
# - deploy: gets the docker image from build and an environment parameter and deploys the docker to the environment
#
  clj-service:
    jobs:
      build:
        working_directory: ~/ci-spread
        docker:
          - image: clashapp/clj:latest
        shell: /bin/bash -eo pipefail
        parameters:
          service:
            type: string
        steps:
          - setup_remote_docker:
              version: 19.03.13
          - checkout
          - restore_cache:
              key: maven-<< parameters.service >>-{{ checksum "deps.edn" }}
          - run:
              name: Lint namespaces
              command: |
                clojure -A:clj-kondo --lint src/clj
              # working_directory: services/<< parameters.service >>
          - attach_workspace: # for libspread.jar
              at: target
          - run:
              name: Build docker image
              command: |
                ./build.sh -b true -p false
                docker save -o << parameters.service >>.tar << parameters.service >>-service:latest
              working_directory: services/<< parameters.service >>
          - save_cache:
              key: maven-<< parameters.service >>-{{ checksum "deps.edn" }}
              paths:
                - ~/.m2/repository
          - persist_to_workspace:
              root: services
              paths:
                - << parameters.service >>/<< parameters.service >>.tar
      # deploy: TODO

executors:
  java-builder:
    docker:
      - image: cimg/openjdk:11.0
    working_directory:  ~/ci-spread/

jobs:
  Build libspread:
    executor: java-builder
    steps:
      - checkout
      - maven-cache/with:
          cache-version: libspread
          cache-key: pom.xml
          steps:
            - run:
                name: Compile
                command: |
                  mvn clean package
                # working_directory: services/db-migration
      - persist_to_workspace:
          root: target
          paths:
            - libspread-1.0.0-SNAPSHOT.jar

  Test api:
    working_directory: ~/ci-spread
    # https://discuss.circleci.com/t/early-preview-new-ubuntu-20-04-linux-machine-executor-image/37281
    # aws-cli 2.0.52
    # docker 19.03.13
    # docker-compose 1.27.4
    # node 12.18.4 (default)
    # node 14.8.0
    # openjdk 1.8
    # openjdk 11.0.8 (default)
    # yarn 1.22.5
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: set ENV variables
          command: |
            # this works because this machine uses bash
            cat env/dev >> $BASH_ENV
            source $BASH_ENV
            echo "env: $SPREAD_ENV"
      - attach_workspace:
          at: target
      - attach_workspace:
          at: services
      - run:
          name: Load docker images
          command: |
            docker load -i services/worker/worker.tar
            docker load -i services/api/api.tar
      - run:
          name: Start docker services
          command: |
            docker-compose -f deployments/dev/docker-compose.yml \
                           -f deployments/dev/services/docker-compose.yml up -d
      - run:
          name: Verify services respond
          command: |
            docker run --network container:dev_mysql appropriate/curl:latest --retry 10 --retry-delay 3 --retry-connrefused http://127.0.0.1:3306/ping
      - run:
          name: api service logs
          background: true
          command: |
            docker logs dev_api --follow
      - run:
          name: worker service logs
          background: true
          command: |
            docker logs dev_worker --follow
      - maven-cache/with:
          cache-version: migration
          cache-key: services/db-migration/pom.xml
          steps:
            - run:
                name: Liquibase migrations
                command: |
                  cd services/db-migration/
                  cp -rf src/main/resources/liquibase liquibase
                  mvn liquibase:update
      - run:
          name: Verify API responds
          command: |
            docker run --network host appropriate/curl:latest --retry 10 --retry-delay 1 --retry-connrefused http://127.0.0.1:3001
      - maven-cache/with:
          cache-version: tests
          cache-key: deps.edn
          steps:
            - run:
                name: Install clojure
                command: |
                  curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
                  chmod +x linux-install-1.10.1.536.sh
                  sudo ./linux-install-1.10.1.536.sh
            - run:
                name: Print versions
                command: |
                  clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - run:
                name: Run test suite
                command: |
                  bin/kaocha

workflows:
  version: 2

  services:
    jobs:
      # ~~~ BUILD ~~~
      - Build libspread
      - clj-service/build:
          name: Build worker service
          service: "worker"
          requires:
            - Build libspread
      - clj-service/build:
          name: Build api service
          service: "api"
          requires:
            - Build libspread
      - Test api:
          requires:
            - Build worker service
            - Build api service
      # ~~~ DEPLOY ~~~
      # TODO (QA/PROD)
